packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.36.0
  lucide-react: ^0.544.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  zod: ^4.1.9
  "@t3-oss/env-core": ^0.13.8
  "@t3-oss/env-nextjs": ^0.13.8
  "@tanstack/react-query": ^5.89.0
  "@trpc/client": ^11.5.1
  "@trpc/tanstack-react-query": ^11.5.1
  "@trpc/server": ^11.5.1
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - esbuild
