export const POSTHOG_EVENTS = {
  "user signed up": "user signed up",
  "user delete": "user delete",
  "profile onboard": "profile onboard",
  "profile created": "profile created",
  "trpc error": "trpc error",
  "paywall presented": "paywall presented",
  "paywall purchase started": "paywall purchase started",
  "paywall purchase completed": "paywall purchase completed",
  "paywall purchase cancelled": "paywall purchase cancelled",
  "paywall purchase error": "paywall purchase error",
  "paywall restore completed": "paywall restore completed",
  "paywall restore error": "paywall restore error",
  "paywall restore started": "paywall restore started",
  "onboarding started": "onboarding started",
  "onboarding completed": "onboarding completed",
  "onboarding abandoned": "onboarding abandoned",
  "onboarding notifications completed": "onboarding notifications completed",
  "onboarding notifications skipped": "onboarding notifications skipped",
  "onboarding rating completed": "onboarding rating completed",
} as const
